- name: Uninstall nginx playbook
  hosts: localhost
  become: true
  tasks:
    - name: Stop nginx
      systemd:
        name: nginx
        state: stopped

    - name: Uninstall nginx
      apt:
        name: nginx
        state: absent # this ensures nginx is uninstalled

    - name: Remove config file
      file:
        path: /etc/nginx/nginx.conf
        state: absent

    - name: Check that we can connect to localhost (pretty much curl)
      ansible.builtin.uri:
        url: http://localhost
      ignore_errors: true 