# example with group names
  # hosts
    # list of hosts
devservers:
  hosts:
    # only this host is fedora based, all other ones are ubuntu based
    # single machine specification
    dev1.internal.net:
      ansible_user: fedora
      # we tell the host where the public key is
      ansible_ssh_private_key_ile;: "~/key.pem"
    dev2.internal.net
    dev3.internal.net
testservers:
  hosts:
    test1.internal.net
    test2.internal.net
    test3.internal.net
  vars:
    # this is the user applied to all hosts
    ansible_user: ubuntu
productionservers:
  hosts:
    prod1.internal.net
    prod2.internal.net
    prod3.internal.net
east-dc:
  hosts:
    dev1.internal.net
    dev2.internal.net
    test1.internal.net
    prod1.internal.net
west-dc:
  hosts:
    dev3.internal.net
    test2.internal.net
    test3.internal.net
    prod2.internal.net
    prod3.internal.net