# "Play" level settings
  # "Task" level settings
    # "Module" level settings 


- hosts: localhost # can also be "all" or "<groupname>", "all" does not include localhost for some reaso
  # become: True                    # do all tasks as a user root
  tasks:
    - name: Install NGINX         # naming a task
      become: True                # this task will run as root
      ansible.builtin.apt:        # module name
        # module arguments
        name: nginx
        state: present
    - name: Create the user dir
      ansible.builtin.file:
        path: /home/ubuntu/folderfromaplaybook
        state: directory
    - name: Restart NGINX
      become: True
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted